services:
  - type: web
    name: my-spring-app
    env: docker
    buildCommand: ./mvnw package -DskipTests && docker build -t my-spring-app .
    startCommand: java -jar app.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mydatabase
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mydatabase
          property: password

databases:
  - name: mydatabase
    databaseName: dbname_xcj9
    user: user