spring.application.name=App


spring.datasource.url=postgresql://user:ZL8zBTQ7QG525h4qDusPZ0oFlQM0b6Dz@dpg-cpvr3juehbks73e1vlo0-a/dbname_xcj9
spring.datasource.username=user
spring.datasource.password=ZL8zBTQ7QG525h4qDusPZ0oFlQM0b6Dz
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

